package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MetadataSignal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String barcode;

	public MetadataSignal() {
	}

	public java.lang.String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(java.lang.String barcode) {
		this.barcode = barcode;
	}

	public MetadataSignal(java.lang.String barcode) {
		this.barcode = barcode;
	}

}