package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ToteInformationSignal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String oeNumber;
	private java.lang.String plRunNumber;
	private java.lang.String shipTo;
	private java.lang.String parentShip;
	private int toteId;
	private java.lang.String toteBarcode;
	private int status;
	private com.ingramcontent.consolidated.labels.model.BarcodeRules barcodeRules;
	private java.lang.String barcodeShip;

	private java.util.List<com.ingramcontent.consolidated.labels.model.Item> items;

	public ToteInformationSignal() {
	}

	public java.lang.String getOeNumber() {
		return this.oeNumber;
	}

	public void setOeNumber(java.lang.String oeNumber) {
		this.oeNumber = oeNumber;
	}

	public java.lang.String getPlRunNumber() {
		return this.plRunNumber;
	}

	public void setPlRunNumber(java.lang.String plRunNumber) {
		this.plRunNumber = plRunNumber;
	}

	public java.lang.String getShipTo() {
		return this.shipTo;
	}

	public void setShipTo(java.lang.String shipTo) {
		this.shipTo = shipTo;
	}

	public java.lang.String getParentShip() {
		return this.parentShip;
	}

	public void setParentShip(java.lang.String parentShip) {
		this.parentShip = parentShip;
	}

	public int getToteId() {
		return this.toteId;
	}

	public void setToteId(int toteId) {
		this.toteId = toteId;
	}

	public java.lang.String getToteBarcode() {
		return this.toteBarcode;
	}

	public void setToteBarcode(java.lang.String toteBarcode) {
		this.toteBarcode = toteBarcode;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public com.ingramcontent.consolidated.labels.model.BarcodeRules getBarcodeRules() {
		return this.barcodeRules;
	}

	public void setBarcodeRules(
			com.ingramcontent.consolidated.labels.model.BarcodeRules barcodeRules) {
		this.barcodeRules = barcodeRules;
	}

	public java.lang.String getBarcodeShip() {
		return this.barcodeShip;
	}

	public void setBarcodeShip(java.lang.String barcodeShip) {
		this.barcodeShip = barcodeShip;
	}

	public java.util.List<com.ingramcontent.consolidated.labels.model.Item> getItems() {
		return this.items;
	}

	public void setItems(
			java.util.List<com.ingramcontent.consolidated.labels.model.Item> items) {
		this.items = items;
	}

	public ToteInformationSignal(
			java.lang.String oeNumber,
			java.lang.String plRunNumber,
			java.lang.String shipTo,
			java.lang.String parentShip,
			int toteId,
			java.lang.String toteBarcode,
			int status,
			com.ingramcontent.consolidated.labels.model.BarcodeRules barcodeRules,
			java.lang.String barcodeShip,
			java.util.List<com.ingramcontent.consolidated.labels.model.Item> items) {
		this.oeNumber = oeNumber;
		this.plRunNumber = plRunNumber;
		this.shipTo = shipTo;
		this.parentShip = parentShip;
		this.toteId = toteId;
		this.toteBarcode = toteBarcode;
		this.status = status;
		this.barcodeRules = barcodeRules;
		this.barcodeShip = barcodeShip;
		this.items = items;
	}

}