package com.ingramcontent.consolidated.labels.utility;

import java.util.Iterator;
import java.util.Map;
import java.util.HashMap;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.kie.api.runtime.process.ProcessContext;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContextUtility implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ContextUtility() {
    }
   
    public static Object getProcessVariable(ProcessContext context, String variable) {
		WorkflowProcessInstance instance = (WorkflowProcessInstance) context.getProcessInstance();
		return instance.getVariable(variable);		
	}
	
	public static void setProcessVariable(ProcessContext context, String variable, Object obj) {
		WorkflowProcessInstance instance = (WorkflowProcessInstance) context.getProcessInstance();
		instance.setVariable(variable, obj);
	}	
	
	public static long getInstanceId(ProcessContext context) {
		return context.getProcessInstance().getId();
	}
	
	public static void initializeMetadata(ProcessContext context, JSONArray jsonArray)   {
		
		if (jsonArray == null || jsonArray.size() == 0) {
			return;
		}
		
	    Iterator<JSONObject> i = jsonArray.iterator();
 
	    // take each value from the json array separately
	    while (i.hasNext()) {
	        JSONObject jsonObject = i.next();
	        updateVariable(context, jsonObject);
	    }
	}
	
	private static void updateVariable(ProcessContext context, 
                                       JSONObject jsonObject)  {
    	
    	if(jsonObject == null) {
    		return;
    	}
    	
    	String key = (String)jsonObject.get("parameterName");
    	String value = (String)jsonObject.get("parameterValue");
    	
    	switch (key) {
			case "libraryServicesKafkaMessageUrl":
				setProcessVariable(context, "libraryServicesKafkaMessageUrl", value);
			break;
		}
    	
    }

}